Validation with Serpent
openmc-dev/validation pull request #3
Opened 2019-04-09 02:35 UTC by amandalund

There are a few changes introduced in this PR. The main addition is the ability to compare OpenMC results to Serpent 2 results in each set of validation scripts. This can be done using the option `-c serpent` (default is `mcnp`). In addition, when creating a cross section library on the fly, the path to an XSDIR directory file should be specified rather than the path to the directory containing the ACE library. This will be used to locate the ACE table and create an HDF5 library for use with OpenMC (and an XSDATA directory file if the comparison is with Serpent). For photon transport calculations with Serpent, a path to the directory containing the additional Serpent photon data is also required. Finally, for neutron transport validation there is now an option to include thermal scattering data by passing in the ZAID of the S(alpha, beta) table, e.g., `-t grph.10t`.

2019-04-09 02:48 UTC, amandalund commented
I also took a look at some of the cases where we were still seeing differences between OpenMC and MCNP with photon calculations (namely high energies, high-Z elements, and compounds), and as expected we see much better agreement with Serpent:

![U-1 0e+02MeV_mcnp](https://user-images.githubusercontent.com/6426426/55769718-5ebaf780-5a47-11e9-828a-dccc1de75730.png)
![U-1 0e+02MeV_serpent](https://user-images.githubusercontent.com/6426426/55769723-637fab80-5a47-11e9-8c73-d4f73a8b34ff.png)

![H20-1 0e+02MeV_mcnp](https://user-images.githubusercontent.com/6426426/55769730-68dcf600-5a47-11e9-8949-aa873833444c.png)
![H20-1 0e+02MeV_serpent](https://user-images.githubusercontent.com/6426426/55769734-6c707d00-5a47-11e9-8468-71048a19aec7.png)

2019-04-09 13:27 UTC, paulromano requested changes
Thanks for the PR! I like how this is set up where you reference the xsdir and then automatically create the xsdata for Serpent. I am noticing quite a bit of duplicated code across our three cases -- we should think about how to reduce some of the redundancy there.

2019-04-09 13:27 UTC, paulromano commented on neutron-physics/model.py
> +        if code not in ['mcnp', 'serpent']:
`if code not in ('mcnp', 'serpent'):`

2019-04-09 13:27 UTC, paulromano commented on neutron-physics/model.py
> +                   f'"serpent".')
Nothing is formatted on the second literal here so you can remove the f-prefix.

2019-04-09 13:27 UTC, paulromano commented on neutron-physics/model.py
> +        if not shutil.which(executable, os.X_OK):
Totally forgot that Python has `which`! I love it

2019-04-09 13:27 UTC, paulromano commented on neutron-physics/model.py
> +        sphere = openmc.Sphere(boundary_type='vacuum', r=1.e9)
Is this intentional?

2019-04-09 13:27 UTC, paulromano commented on neutron-physics/model.py
> +        lines.append('+1 so 1.e9')
Ok, now I'm more confused. I had to look this up to figure out it is a white boundary condition. What is the intent of this change?

2019-04-09 13:27 UTC, paulromano commented on neutron-physics/validate.py
> +parser.add_argument('-l', '--library', type=str, help='XSDIR directory file. '
Maybe we should make this `-x` / `--xsdir` to be more explicit?

2019-04-09 13:27 UTC, paulromano commented on photon-physics/model.py
> +        if code not in ['mcnp', 'serpent']:
use tuple instead of list

2019-04-09 13:27 UTC, paulromano commented on photon-physics/model.py
> +                   f'"serpent".')
No f-prefix needed on second literal

2019-04-09 13:27 UTC, paulromano commented on photon-physics/model.py
> +        if not re.match('0[1-4]p|12p', suffix):
Isn't there an 84p too?

2019-04-09 13:27 UTC, paulromano commented on photon-physics/model.py
> +        # Turn on Doppler broadening of Compton scattered photons (on by
Should that be "off by default"?

2019-04-23 23:00 UTC, amandalund commented
Sorry for the delay! I addressed those comments and did some reorganizing to get rid of a bunch of the redundant code.

2019-04-24 03:28 UTC, paulromano commented on setup.py
> +    description=('A collection of validation scripts for OpenMC'),
Parentheses are superfluous

2019-04-24 03:28 UTC, paulromano commented on README.md
> +- **photon-production** -- A set of scripts for validating photon production in OpenMC. The scripts generate a broomstick problem where monoenergetic neutrons are shot down a thin, infinitely long cy
README needs updating since these directories no longer exist

2019-04-24 03:28 UTC, paulromano commented on setup.py
> +            'validate-photon-production=validation.photon_production:main'
Maybe we should prefix these scripts with `openmc-` to make it clear what they are related to

2019-04-24 03:28 UTC, paulromano commented on validation/neutron_physics.py
> +class NeutronPhysicsModel(object):
`class NeutronPhysicsModel:` will suffice

2019-04-24 20:44 UTC, paulromano approved these changes

2019-04-24 20:44 UTC, merged